services:
  mongodb:
    image: mongo:7
    container_name: talentbridge-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-admin}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-talentbridge}
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
