spring:
  application:
    name: talent-bridge

  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:talentbridge}
      username: ${MONGO_USERNAME:admin}
      password: ${MONGO_PASSWORD:admin}
      authentication-database: admin

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o

server:
  port: 8080
